export interface Library { id: string; name: string; description: string; allowRemoteModels: boolean; autoReviewAgentSubmissions: boolean; reviewProviderId?: string; createdAt: string; updatedAt: string }
export interface Chunk { id: string; documentId: string; text: string; location: Record<string, unknown>; contentHash: string }
export interface Document { id: string; libraryId: string; title: string; mediaType: string; sourcePath?: string; sourceUrl?: string; objectPath?: string; contentHash?: string; status: 'pending'|'pending_review'|'approved_pending_index'|'rejected'|'ready'|'failed'|'source_missing'; error?: string; tags: string[]; favorite: boolean; createdAt: string; updatedAt: string }
export interface DocumentDetail extends Document { preview: Chunk[] }
export interface KnowledgeDirectoryEntry { uri: string; revision: number; title: string; description: string; type: string; subtype?: string; language: 'zh-CN'|'en'; primaryPath: string[]; classifications?: Record<string, string[]>; tags: string[]; matchedSectionIds: string[]; matchReason: string; flags: string[]; trust: string; conflictUris?: string[] }
export interface KnowledgeSearchResponse { results: KnowledgeDirectoryEntry[]; nextCursor?: string }
export interface KnowledgeSection { id: string; heading: string; content: string }
export interface KnowledgeRevision { libraryId: string; knowledgeId: string; uri: string; revision: number; payload: { schema: string; id: string; revision: number; title: string; description: string; type: string; subtype?: string; language: 'zh-CN'|'en'; aliases?: string[]; primaryPath?: string[]; classifications?: Record<string, string[]>; tags?: string[]; sections: KnowledgeSection[]; sources?: { id: string; resource: string; title?: string; locator?: Record<string, unknown>; snapshot?: { status?: string; content_hash?: string; captured_at?: string } }[]; relations?: { type: string; target: string; target_revision?: number }[]; derivation?: Record<string, unknown> }; markdown: string; contentHash: string; status: 'draft'|'approved_pending_index'|'rejected'|'stable'|'deprecated'; flags: string[]; stable: boolean; createdAt: string; submittedBy?: string }
export interface Job { id: string; kind: string; status: string; progress: number; message?: string; createdAt: string; updatedAt: string }
export interface Skill { id: string; name: string; systemRole?: string; description: string; compatibility?: string; license?: string; metadata?: Record<string, string>; allowedTools?: string; rootPath: string; entryPoint: string; contentHash: string; status: 'ready'|'failed'|'invalid'; error?: string; fileCount: number; usesLibraryIds: string[]; requiresLibraryIds: string[]; createdAt: string; updatedAt: string }
export interface SkillFile { path: string; size: number; sha256: string; mediaType: string; url?: string; content?: string }
export interface SkillManifest { skill: Skill; root: string; entryPoint: SkillFile; files: SkillFile[] }
export interface Provider { id: string; name: string; kind: 'openai'|'anthropic'|'lmstudio'|'custom'; baseUrl: string; model: string; embeddingModel: string; local: boolean; apiKey?: string }
export interface AgentToken { id: string; name: string; scopes: ('mcp_read'|'mcp_manage')[]; libraryIds: string[]; secret?: string; createdAt: string; revokedAt?: string }
export interface KAHReviewRecord { id: string; submissionId: string; reviewerType: 'model'|'human'; reviewer: string; decision: 'approve'|'reject'|'needs_human'; reason: string; createdAt: string }
export interface KAHSubmission { id: string; libraryId: string; knowledgeUri: string; revision: number; mode: 'create'|'propose_revision'; reviewStatus: 'pending_review'|'approved_pending_index'|'rejected'|'published'; validation: Record<string, unknown>; title: string; summary: string; tags: string[]; provenance: Record<string, unknown>; clientSubmissionId: string; submittedByTokenId?: string; markdown?: string; reviews?: KAHReviewRecord[]; createdAt: string; updatedAt: string }
export interface SavedSearch { id: string; name: string; query: string; libraryIds: string[]; tags: string[] }
export interface VirtualFolder { id: string; libraryId: string; name: string; parentId?: string }
export interface SourceWatch { id: string; libraryId: string; rootPath: string; recursive: boolean; enabled: boolean; lastScanAt?: string; lastMessage?: string }
