packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@scarf/scarf'
  - electron
  - electron-winstaller
  - esbuild

confirmModulesPurge: false
allowBuilds:
  '@scarf/scarf': false
  electron: true
  electron-winstaller: true
  esbuild: true
